services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: password_manager_development
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    links:
      - mongo

  selenium:
    image: seleniarm/standalone-chromium
    shm_size: 2g
    ports:
      - 4444:4444

  passwordmanager:
    build:
      context: .
      args:
        ZSCALER_CERT: ${ZSCALER_CERT:-}
    command: /bin/sh -c "/password-manager/entrypoint.sh"
    restart: "no"
    links:
      - mongo
    volumes:
      - .:/password-manager
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: "true"
    ports:
      - 3000:3000

  passwordmanager-test:
    build:
      context: .
      args:
        ZSCALER_CERT: ${ZSCALER_CERT:-}
    environment:
      RAILS_ENV: test
      SELENIUM_REMOTE_URL: http://selenium:4444
      APP_HOST: passwordmanager-test
    links:
      - mongo
      - selenium
    volumes:
      - .:/password-manager

volumes:
  mongodb:
