version: '3.2'

services:
  db:
    restart: always

  memcache:
    image: memcached:alpine
    restart: always

  as:
    image: alkcxy/bilancio:${BILANCIO_VERSION}
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    restart: always
    links:
      - memcache
    environment:
      RAILS_ENV: production
    volumes:
      - ../../../shared/log:/bilancio/log

  dj:
    image: alkcxy/bilancio:${BILANCIO_VERSION}
    restart: always
    command: /bin/sh -c "rm -f tmp/pids/delayed*.pid && bundle exec bin/delayed_job run"
    environment:
      RAILS_ENV: production
    env_file:
      - .env
    links:
      - db
    volumes:
      - ../../../shared/log:/bilancio/log

  pe:
    image: alkcxy/bilancio:${BILANCIO_VERSION}
    restart: always
    command: /bin/sh -c "prometheus_exporter"
    environment:
      RAILS_ENV: production
    env_file:
      - .env
    links:
      - as
    volumes:
      - ../../../shared/log:/bilancio/log

  web:
    image: nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
      - as
    volumes:
      - ../../../shared/letsencrypt/certs:/etc/letsencrypt
      - ../../../shared/letsencrypt/www:/var/www/certbot
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - assets:/bilancio/public/assets
      - ./nginx/robots.txt:/bilancio/public/robots.txt
      - ../../../shared/log:/bilancio/log
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
    volumes:
      - ../../../shared/letsencrypt/certs:/etc/letsencrypt
      - ../../../shared/letsencrypt/www:/var/www/certbot
      - ../../../shared/log:/var/log/letsencrypt

volumes:
  assets:
