version: '3.5'

services:
  mongo:
    image: bitnami/mongodb
    restart: always
    env_file:
      - .env
    environment: 
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - mongodb:/bitnami/mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
    links:
      - mongo

  as:
    build: .
    command: /bin/sh -c "/password-manager/entrypoint.sh"
    restart: "no"
    links:
      - mongo
    volumes:
      - .:/password-manager
    env_file:
      - .env
    ports:
      - 3000:3000

volumes:
  mongodb: