version: '3.2'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  as:
    build: .
    command: /bin/sh -c "/password-manager/entrypoint.sh"
    restart: "no"
    links:
      - mongo
    volumes:
      - .:/password-manager
    environment:
      RAILS_ENV: development
      # SECRET_PM is a base64 encrypted key 
      # (generate it with https://ruby-doc.org/stdlib-2.4.0/libdoc/openssl/rdoc/OpenSSL/Cipher.html#class-OpenSSL::Cipher-label-Choosing+a+key)
      # then Base64.encode64 key
      SECRET_PM: WkFKaXUzaGlRN3VoOFFEc1NTRmtHc25pRGRvbmZpMG8=\n
      SECRET_KEY_BASE: fdbdc02110a05b6a251d52e7ec43df7257b547b61238b59bc909d7645d1aadc36daa50d79fe8776ea43e658b1a4f41cca736f07bd173ff1a5d220622b3e465d7
      RAILS_LOG_TO_STDOUT: 1
    ports:
      - 3000:3000
